### ISSUE TITLE
Sample with ASP MVC Core views

### ISSUE THREAD

**Issue by fasteddys** [yjs/y-websocket#109]
hello, this is fascinating, can you include a sample to use with ASP MVC core views please

**Comment by dmonad** [comment]
Hi @fasteddys,

This is a bit out-of-scope for this project. I don't have a Windows computer or know what an ASP MVC Core View is..

There's a C# implementation of Yjs that could be helpful to build a .Net backend for Yjs. If you find somebody who can implement this, I'd be happy about a contribution that adds an example on how to do it.

https://github.com/yjs/ycs
