### ISSUE TITLE
[Question] Is there an event to identify that data has been uploaded to the server?

### ISSUE THREAD

**Issue by lijie1129** [yjs/y-websocket#110]
**My scenario**: create a document locally, input some content, and then establish a connection through y-websocket to upload it to the server. 

**The question** is: when to close this connection(wsProvider)?

_I currently use setTimeout to destroy the wsProvider after 5 seconds. But I don't think it's elegant._

**Comment by dmonad** [comment]
Please, questions go to discuss.yjs.dev
