### ISSUE TITLE
Incorrect handling of y-protocols/auth messages

### ISSUE THREAD

**Issue by mifopen** [yjs/y-websocket#117]
**Describe the bug**
`readAuthMessage` passes Y.Doc instance to `permissionDeniedHandler` (or whatever you gave it as the second argument)
But `permissionDeniedHandler` in `y-websocket.js` thinks it will be a provider https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js#L62

**To Reproduce**
1. Send auth message from server
2. See `Permission denied to access undefined` in logs

**Expected behavior**
See `Permission denied to access <URL> or smth` in logs

**Comment by dmonad** [comment]
Thanks, I fixed this. This will be included in the next release.
