### ISSUE TITLE
Incorrect lib0 peerDependency version

### ISSUE THREAD

**Issue by mifopen** [yjs/y-websocket#118]
Looks like you need to set `lib0` peerDependency to at least `0.2.51`. Otherwise, passing `provider` as `origin` parameter of `publish` function doesn't make any effect and messages are handled by the "origin" instance as well.
As a result,the  "origin" instance handles the final awareness update on destroying/disconnecting the provider and thus holding itself in the "on" state for others on reconnection :)

**Comment by dmonad** [comment]
I'm sorry, I don't understand this bug report. How do I reproduce this? lib0 is already a dependency of y-websocket and I don't think it makes sense to add it as a peerDependency.
