### ISSUE TITLE
Is beforeunload a correct event for reseting awareness state?

### ISSUE THREAD

**Issue by mifopen** [yjs/y-websocket#119]
Shouldn't it be just `unload`. `beforeunload` is often used to ask users about unsaved changes. It means that the user will be "disconnected" from the awareness protocol until they choose, for example, "exit without saving", "cancel" or "save".

**Comment by dmonad** [comment]
Can you try out whether disconnecting will still work if we do it in the unload event?

**Comment by mifopen** [comment]
Yes, it does work

**Comment by dmonad** [comment]
Thanks for verifying. Added this change and made a release.
