### ISSUE TITLE
Doesn't work with React.strictMode

### ISSUE THREAD

**Issue by arvid220u** [yjs/y-websocket#124]
In React strict mode, the provider will be created twice, with one of the two being destroyed immediately. This seems to make the syncing not work. My guess is that it has to do with the globals being used (e.g. `messageHandlers`).

If I have time to work on this I will submit a pull request!

**Comment by cmmartin** [comment]
Can't you use memoization to prevent it from being created twice?

**Comment by dmonad** [comment]
This doesn't seem to be an issue that can be fixed in y-websocket. Next time, please fill out the bug report form.
