### ISSUE TITLE
WebSocket provider allows redirect

### ISSUE THREAD

**Issue by davidbrochart** [yjs/y-websocket#125]
Hi @dmonad,
It looks like if a WebSocket endpoint returns a redirect to another WebSocket endpoint, the WebSocket provider doesn't follow the redirect.
Is that correct? If so, would it be possible to allow redirects?

**Comment by dmonad** [comment]
The Websocket API in the browser doesn't have such a configuration, I think..

Not sure how one would implement this.

**Comment by dmonad** [comment]
https://stackoverflow.com/questions/46962881/is-it-possible-to-seamlessly-redirect-websockets

The Q above seams to explain the situation. The browser usually doesn't follow redirects. You could implement a polyfill that supports redirects as explained in the A above.

**Comment by dmonad** [comment]
FYI: y-websocket accepts a Websocket polyfill.

**Comment by davidbrochart** [comment]
Interesting, thanks @dmonad !
