### ISSUE TITLE
[Feature Request]: Support emit peers

### ISSUE THREAD

**Issue by Deuscx** [yjs/y-websocket#135]
**Checklist**

[x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[  ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the solution you'd like**
Is it able to support emit `peers` event like https://github.com/yjs/y-webrtc

**Additional context**
<img width="759" alt="image" src="https://user-images.githubusercontent.com/48537979/225883102-dfaaddd9-5bf2-4748-bdbc-59dff70b3a80.png">

**Comment by dmonad** [comment]
Since y-websocket only connects to a server, the `peers` event would be the same as the `connected` event. 

If you want to read who currently is in a room, you should use the awareness API.
