### ISSUE TITLE
Can't get text data on server

### ISSUE THREAD

**Issue by rodshtein** [yjs/y-websocket#167]
##  Packages
y-protocols: 1.0.6
y-websocket: 1.5.3
yjs: 13.6.10
ws: 8.16.0

node: 18.18.2

## Description 
It's almost last node server implementation, i just add couple string to log events: 

![image](https://github.com/yjs/y-websocket/assets/13717428/4ffe935d-4ccb-4cab-8487-763c8b878c10)

… and i get nothing (sync works fine anyway):

![image](https://github.com/yjs/y-websocket/assets/13717428/0950ec21-d6d3-49f9-aba5-211bb2fbce80)

i even tried HTTP callback with same result: 

![image](https://github.com/yjs/y-websocket/assets/13717428/a2ece9bd-178e-4ee3-9581-4ce00da0ab4c)

But for Array all works fine:

![image](https://github.com/yjs/y-websocket/assets/13717428/c61f0e80-56ea-49dc-8d4a-9dcdc53a56d5)

**Comment by dmonad** [comment]
I can't reproduce the issue with this little information.

I guess that when you debug the issue yourself you will find that 'code' is not a Y.Text on the client-side...

**Comment by dmonad** [comment]
Try changing getText to getArray

**Comment by rodshtein** [comment]
@dmonad 

On client side it's definitely Text. It's Codemirror binding

![image](https://github.com/yjs/y-websocket/assets/13717428/bdfb19c1-28d6-4099-8657-a53a02e32278)


And i tried to  use shadow doc — and all works fine. Looks like bug for me

![image](https://github.com/yjs/y-websocket/assets/13717428/c02a1915-cf76-44a2-bacf-1b5182787f5b)
![image](https://github.com/yjs/y-websocket/assets/13717428/b673e902-8f1f-4f19-a9b4-da01a868196d)

**Comment by rodshtein** [comment]
Ok, json works, but why? Why text type become json, and then Text again?
![image](https://github.com/yjs/y-websocket/assets/13717428/0cb18b0e-0c72-4275-ac4e-2284746d1ee0)
![image](https://github.com/yjs/y-websocket/assets/13717428/e68f7f41-8f51-4329-a99f-f96a37774360)

**Comment by dmonad** [comment]
I don't know how you modified the code. The issue is not reproducible. My guess is that it has something to do with the hooks you set up

**Comment by rodshtein** [comment]
Hm, i don't use any hooks, it's almost a pure r&d project.  Ok, i will try to reproduce it without ui framework. Will back soon.
