### ISSUE TITLE
Persistance directory

### ISSUE THREAD

**Issue by g0dzcsgo** [yjs/y-websocket#169]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Okay, so I want to make it so whenever I close down the socket server the persistance database gets removed

I logged the persistenceDir inside of utils.js in the bin of the y-websocket in my node_modules
But its undefined, so I dont understand how its saving? Or where? Ive restarted it a couple of times but still saved?

**To Reproduce**
3. Open console

**Expected behavior**
I expect to be able to set persistance directory

**Environment Information**
 - Browser / Node.js [e.g. Chrome, Firefox, Node.js] Chrome
 - Yjs version and the versions of the y-* modules you are using [e.g. yjs v13.0.1, y-webrtc v1.2.1]. Use `npm ls yjs` to find out the exact version you are using. Latest of all

**Additional context**
I am trying to make persistance remove when I close my socket server.

**Comment by dmonad** [comment]
If it's not persisted to disk, then it might live on one of the clients, indexeddb, or wherever. Yjs documents are kinda hard to delete..

Please read the ticket notes next time..
