### ISSUE TITLE
Websocket support for node

### ISSUE THREAD

**Issue by dmonad** [yjs/y-websocket#17]
See https://discuss.yjs.dev/t/nodejs-support-for-y-websocket/132

**Comment by dmonad** [comment]
@canadaduane

This is now supported as a third parameter. 

`new WebsocketProvider(url, room, ydoc, { WebSocketPolyfill: MyWebsocketPolyfill })`. I haven't tested this with nodejs and `ws` yet, but I imagine this is how it should work.

**Comment by codesiddhant** [comment]
not working at all
