### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by micrology** [yjs/y-websocket#23]
There are two issues.  I am reporting them as separate issues because I don't know whether they are related, but they might be.

**Describe the bug**
When running y-websocket, version 1.3.1, the memory used by `node` increases until it exceeds the RAM available.

**In more detail**
Using the set up recommended in the README, i.e. 
```
PORT=1234 YPERSISTENCE=./dbDir node ./node_modules/y-websocket/bin/server.js
```
the memory used by node grows unreasonably.  When y-websocket is started, it looks like this:
```
Private  +   Shared  =  RAM used	Program
141.3 MiB + 411.5 KiB = 141.7 MiB	node
```
Twenty four hours later, it looks like this:
```
 1.6 GiB + 324.5 KiB =   1.6 GiB	node
```
At this point I have to restart it as I don't have that much free RAM.

**Expected behavior**
What I am expecting is that the RAM used by `node` remains more or less constant

**Environment**

System: a AWS EC2 Linux 2 server
Node: v14.4.0
Implemented using a system service, with:
```
[Unit]
Description=websocket-server
[Service]
ExecStart=/data/cress/prism/node_modules/.bin/y-websocket-server
Restart=always
RestartSec=10
User=root
Group=root
Environment='PATH=/home/ec2-user/.nvm/versions/node/v14.4.0/bin' 'YPERSISTENCE=/data/cress/prism/dbDir'
# Output to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=websocket-server
[Install]
WantedBy=multi-user.target
```

**Comment by dmonad** [comment]
Thanks, I'll look into it

**Comment by garsdle** [comment]
Hi @dmonad any movement on this? We are looking to update our lib version but concerned about the memory leak.

**Comment by dmonad** [comment]
Hi @garsdle , I can confirm that the memory usage increases over time, but I'm currently to busy to actually profile the bug and provide a fix for it. 

You can probably find the memory issue yourself if you create two memory snapshots (the second one after memory usage increased by 100 MB) in the v8 developer console and compare the difference. It will probably take a few hours until you get meaningful results. If you tell me which objects consume the most memory I can probably narrow down the issue.

**Comment by ellisonbg** [comment]
HI all, I everything setup to debug this. Quick question: are you seeing the memory leak during periods where there are lots of document edits going through the WS server, or during periods where it is mostly idle?

**Comment by ellisonbg** [comment]
I ran my test for 1 hour, making random edits to the doc every 10ms. Memory grew by around 100MB during this time. I can send the allocation timeline to anyone who is interested. Here is a screenshot that shows the results omitting the initial startup and final shutdown:

![Screen Shot 2020-10-03 at 12 05 45 PM](https://user-images.githubusercontent.com/27600/94999877-5296f400-0571-11eb-8890-1efea640c7b5.png)

The objects consuming the most memory are Item, ID, ContentString, array, string. Under array, the top few entires are arrays of Items (the other arrays listed are listed as internal array, code deopt data, etc.).

**Comment by micrology** [comment]
Hi Brian,

There is more at https://github.com/yjs/y-websocket/issues/24

The last comment of that thread includes a link to a movie showing what happens at the client end. You will see that there is a disconnect/connect every 30 seconds – not always, but (I think) whenever some kind of glitch at one or other end generates an error 503, and the server connection then goes into this connect/disconnect cycle.

In response to your question, I’ve had the memory used by node grow to 1.5 GB or more (!) with just one idle client, with that client connecting and disconnecting every 30 seconds.

As a work round, I am using a cron job to restart the server every 24 hours, otherwise, the server just runs out of memory and has to be rebooted.  I just had a look and although all clients have been idle all day, I see:

Private  +   Shared  =  RAM used Program
557.9 MiB + 306.5 KiB = 558.2 MiB           node

I do hope you do find the bug – it is inhibiting me from distributing my app.

Best wishes,

Nigel



Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173

**Comment by ellisonbg** [comment]
@micrology thanks for clarifying. Has anyone observed memory growth in a situation other than when clients are disconnecting/reconnecting? In looking through the server code, I see there is a closure used for the ping `setInterval`:

https://github.com/yjs/y-websocket/blob/master/bin/utils.js#L224

When I run a test with the client disconnecting/reconnecting the count of those closures increases without bound. There may be situations when clients are disconnecting/reconnecting that result in `clearInterval` not ever being called.

**Comment by ellisonbg** [comment]
@micrology can you test the PR that I just opened that tries to fix the clearInterval issue above: #30

**Comment by micrology** [comment]
I’m testing.  No problems yet, but it can take time…

I’ll keep my fingers crossed.

Nigel



Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173

**Comment by dmonad** [comment]
I merged @ellisonbg 's PR because it definitely fixed some unintended behavior. It is published in v1.3.4.

I'll leave it to you @micrology to close this bug. Let us know if there is still a memory leak.

Thank you all for contributing helpful profiling data and @ellisonbg  for debugging and providing a fix for this issue :heart:

**Comment by ellisonbg** [comment]
@micrology keep us posted on the outcome!

@dmonad thanks for the quick review+merge!

**Comment by micrology** [comment]
The modified util.js version of y-websocket has been running  for 9 hours and I haven't seen any disconnect/connect behaviour so far, so I am going to assume that this bug is now solved and will close the issue.  Many thanks to @ellisonbg for his excellent debugging!

**Comment by ellisonbg** [comment]
Fantastic!
