### ISSUE TITLE
Export `docs` in utils.js

### ISSUE THREAD

**Issue by canadaduane** [yjs/y-websocket#27]
**Is your feature request related to a problem? Please describe.**
I'd like to use `y-websocket` as a dependency to my server, rather than copy-paste code from `y-websocket`. Currently, the code in `bin/utils.js` does not expose its `docs` data, so my server code cannot access the internal docs.

Specifically: I am trying to create an HTTP API endpoint that copies one YDoc to another YDoc, and I believe I need access to the internal `docs` map to do so.

**Describe the solution you'd like**
I'd like there to be an `exports.docs = docs` after `const docs = new Map()`

**Describe alternatives you've considered**
I'm looking for guidance--is this a reasonable thing to export? Should I create a PR?

**Comment by dmonad** [comment]
Sure, that isn't a problem. I just published a new release that exports `docs`. `@1.3.3`

**Comment by canadaduane** [comment]
Thanks!
