### ISSUE TITLE
Alert message shown regularly while websocket attempts to reconnect

### ISSUE THREAD

**Issue by tommoor** [yjs/y-websocket#31]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I'm able to reproduce receiving this alert with ease by killing the websocket server locally and letting it retry to connect for a few minutes. Reporting as requested – I feel strongly that this alert should be changed out for an error or warning in the console btw, as it's existence makes deploying in production a problem.

**Screenshots**

![image](https://user-images.githubusercontent.com/380914/95390648-96a83280-08aa-11eb-9ca8-ea0fc4af03f6.png)

![image](https://user-images.githubusercontent.com/380914/95390761-b8a1b500-08aa-11eb-910a-2479e9bfe829.png)

You can see the error being triggered regularly, but also quite erratically.
 
![image](https://user-images.githubusercontent.com/380914/95390856-e2f37280-08aa-11eb-86a1-306ee6442eca.png)

**To Reproduce**
1. Use the module, connect to a socket server successfully
2. Kill the socket server process
3. Leave the frontend retrying for several minutes

**Expected behavior**

There should be no alert message shown to users.

**Environment Information**
 - Browser: Chrome latest (85)
 - version: yjs@13.4.0, y-websocket@1.3.3

**Additional context**

Happy to provide any extra debugging or info that might be needed

**Comment by tommoor** [comment]
This message seems to be guarded by `resyncInterval` being enabled so I'm just disabling that option for now

**Comment by dmonad** [comment]
I was working with someone who reported (and showed logs) that the first sync message went missing. This would mean that in some browsers the first message on the websocket protocol can get lost which is very disturbing.

The issue seems to happen when a client connects through a VPN to a different region. It was only happening to a non-developer and I wanted to confirm what is happening.

I haven't head back from that user. So I will remove the message. 

resyncInterval should fix the issue anyway. I'm not sure what else I can do.

**Comment by tommoor** [comment]
Any truth in my observation that rsyncinterval should be cleared when the connection is closed?

**Comment by dmonad** [comment]
When the connection is closed then then `ws` object should be set to null (https://github.com/yjs/y-websocket/blob/5a36d77d481fb31119042b7ef0f37bb4924fb746/src/y-websocket.js#L94). 

Then `resyncInterval` shouldn't do anything anymore.. (https://github.com/yjs/y-websocket/blob/5a36d77d481fb31119042b7ef0f37bb4924fb746/src/y-websocket.js#L222)

So how do you have a closed connection and still have the resyncInterval send messages?

Do you overwrite the onclose property? Or is there an edge case I'm not aware of?

**Comment by tommoor** [comment]
Not overwriting anything. It was happening during the retry connection loop once the server is killed, so there might be an edge-case – If I pin it down I'll file another ticket/PR.

**Comment by dmonad** [comment]
That would be great, thanks!
