### ISSUE TITLE
Using y-websocket in Node.js: Depends on `window` 

### ISSUE THREAD

**Issue by hanspagel** [yjs/y-websocket#55]
**Describe the bug**
I’m trying to use y-websocket in Node.js (for testing purposes). As described in the README I’m passing `ws` as a WebsocketPolyfill, like this:

```js
const wsProvider = new WebsocketProvider('ws://localhost:1234', 'my-roomname', doc, { WebSocketPolyfill: require('ws') })
```

When I try to run this code there are two parts that expect to run in a Browser context:

1. https://github.com/yjs/y-websocket/blob/02f691d89c8cfea884d9f9fa98f0ff192b0eb7d9/src/y-websocket.js#L279-L281
2. https://github.com/dmonad/lib0/blob/01005b5435f7c4e91fb8ea9933e734cc0a6c3451/broadcastchannel.js#L45:L45

**To Reproduce**
1. Execute the above code in a Node.js environment
2. See errors

**Expected behavior**
I’d expect y-websocket to use `window` only when available.

**Environment Information**
 - Node.js
 - Latest version of y-websocket

**Additional context**
I don’t know if it’s dumb using y-websocket in Node.js, but using Cypress feels like overkill. ¯\\\_(ツ)\_/¯

**Comment by hanspagel** [comment]
Oops, duplicate of #51.

**Comment by kriskbx** [comment]
Thanks a bunch for working on lib0. But there's still a window reference in y-websocket itself: https://github.com/yjs/y-websocket/blob/9d7e5eaec89050a191b301c45e484357f1c44ae8/src/y-websocket.js#L279
