### ISSUE TITLE
Make y-websocket run on node.js so that websocket server for y-websocket can be tested

### ISSUE THREAD

**Issue by kapv89** [yjs/y-websocket#65]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
I wrote tests for a ws-server for y-websocket using `lib0/testing` (since I don't know any other testing-lib that works with esm). When I tried to run those tests, I got an error message regarding usage of `window` in y-websocket ([from this line](https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js#L279)). These type of things prevent running y-websocket in a node.js environment and writing and running automated tests for it

**Describe the solution you'd like**
y-websocket should be runnable on node.js. If some help is needed, then I can copy over the testing-code which tries to use y-websocket in node.js env from my private repo to a public repo, and that repo can be used to verify if y-websocket can be run on backend.

**Describe alternatives you've considered**
not testing the ws server which y-websocket connects to is the only alternative, but it doesn't bring much confidence

**Additional context**
test-code:
```typescript
import * as t from 'lib0/testing.js';
import * as Y from 'yjs';
import faker from 'faker';
import WS from 'ws';
import {WebsocketProvider} from 'y-websocket';
import { nockCheckAuth, nockGetUpdates, nockPostUpdate, wsUrl } from './index.js';

export const testSingleDoc = async (tc: t.TestCase) => {
  const id = faker.datatype.uuid();
  const token = faker.lorem.word();
  const doc = new Y.Doc();
  const updates: string[] = []

  nockCheckAuth(token);
  nockGetUpdates(token, id, updates);
  nockPostUpdate(token, id, updates);
  const wsProvider = new WebsocketProvider(wsUrl(), id, doc, {params: {token}, WebSocketPolyfill: WS as any})

  const items = doc.getArray('items');
  items.push([faker.random.word()]);

  await new Promise<void>(resolve => setTimeout(resolve, 1000));
  wsProvider.destroy();
}
```

error-message

```
[1/1] app: single doc
  ReferenceError: window is not defined
      at new WebsocketProvider (/home/k/Projects/proj/yjs-proto/sw/crdt-ws/node_modules/y-websocket/src/y-websocket.js:280:5)
      at testSingleDoc (file:///home/k/Projects/proj/yjs-proto/sw/crdt-ws/src/__tests__/app.test.ts:17:22)
      at run (file:///home/k/Projects/proj/yjs-proto/sw/crdt-ws/node_modules/lib0/testing.js:158:17)
      at runTests (file:///home/k/Projects/proj/yjs-proto/sw/crdt-ws/node_modules/lib0/testing.js:552:27)
      at file:///home/k/Projects/proj/yjs-proto/sw/crdt-ws/src/__tests__/main.ts:8:11
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failure: single doc in 3.54ms
repeat: npm run test -- --filter "\[1/" 

> 1 test failed
```

**Comment by dmonad** [comment]
Fixed it in y-websocket@1.3.12
