### ISSUE TITLE
[Question] subDocument vs WebSocket connection ?

### ISSUE THREAD

**Issue by jarone** [yjs/y-websocket#66]
hi, I'm newer.

About subDocuments sync each other based on y-websocket.

I had read the Document(https://docs.yjs.dev/api/subdocuments), and found some confuses.

The one of them is:

Does there must create a separated WebSocket connection after invoke load() ?

Can I use only single WebSocket connection to Sync all YDocs?

Is there any detail information about it?

**Comment by dmonad** [comment]
When using y-websocket, you have to create a single WebSocket connection for each document. There are efforts to synchronize several subdocuments over a single y-websocket connection.

This is the algorithm that I want to implement eventually: https://discuss.yjs.dev/t/question-regarding-updates-and-state-vectors-in-y-leveldb/399/6?u=dmonad

Please use https://discuss.yjs.dev/ for questions in the future.

Cheers,
 Kevin

**Comment by jarone** [comment]
Thanks, Kevin. 🤝
