### ISSUE TITLE
WebsocketProvider instance leaving open handles after calling .destroy in node.js

### ISSUE THREAD

**Issue by kapv89** [yjs/y-websocket#68]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
When y-websocket is used in node.js environment (for writing tests) with [`ws`](https://www.npmjs.com/package/ws) providing the `WebSocketPolyfill`, it works fine, but after calling `yWsProvider.destroy()`, y-websocket leaves some unknown handles open which prevent the node process from exiting.

**To Reproduce**
1. clone [this repo](https://github.com/kapv89/yjs-scalable-ws-backend) and `cd` into it
2. run `npm run ci`
3. run `cp .env.example .env.test.local`
4. fill up `.env.test.local`
5. run `npm run watch`, and then open a new terminal
6. run `npm run test` - observe that the tests do not exit - forcefully terminate the test process with `Ctrl+C`
7. go to `src/__tests__/app.test.ts`, comment out line 21 & line 27 - wait for `tsc` to finish compilation
8. run `npm run test` again - observe that tests exit

**Expected behavior**
If you follow the steps in **To Reproduce**, then ideally in step no. 6, the process should exit, with `wsp.destroy()` successfully terminating everything.

**Screenshots**
NA

**Environment Information**
 - Node.js v16.1.0
 - y-websocket@1.3.14, yjs@13.5.6

**Additional context**
This bug is important for making the websocket server for y-websocket testable

**Comment by dmonad** [comment]
Hi @kapv89, thanks for opening this issue. It would help me greatly if you could find out which handler is still open.

**Comment by kapv89** [comment]
hi @dmonad 

below is the output from [`wtfnode`](https://www.npmjs.com/package/wtfnode)

```

> crdt-backend@1.0.0 test
> node -r source-map-support/register -r dotenv/config dist/__tests__/main.js dotenv_config_path=.env.test.local

[1/1] app: single doc
Success: single doc in 1.06s
repeat: npm run test -- --filter "\[1/" 

All tests successful! in 1.06s
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
- Sockets:
  - (?:?) -> localhost:? (destroyed)
  - 127.0.0.1:40838 -> 127.0.0.1:6379
  - 127.0.0.1:40840 -> 127.0.0.1:6379
- Timers:
  - (1 ~ 1 undefined) setupWS @ file:///home/k/Projects/proj/yjs-proto/exp/crdt-backend/node_modules/y-websocket/src/y-websocket.js:123
- Intervals:
  - (3000 ~ 3 s) (anonymous) @ file:///home/k/Projects/proj/yjs-proto/exp/crdt-backend/node_modules/y-protocols/awareness.js:59
```

**Comment by dmonad** [comment]
It seems that it's the Awareness instance's fault. The Awareness instance is not destroyed because it could be used by other providers.

You will probably fix the issue by doing `provider.awareness.destroy()` before calling `provider.destroy()`.

**Comment by kapv89** [comment]
Thanks that fixes it. Closing the issue.
