### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by micrology** [yjs/y-websocket#69]
**Bug**
Running 
```
HOST=localhost PORT=1234 npx y-websocket-server
```
yields
```
ReferenceError: require is not defined
```
**To reproduce:**
```
npm install y-websocket
```
(installs 1.3.14)
Then
```
HOST=localhost PORT=1234 npx y-websocket-server
```

which generates:
```
file:///xxxxxxxx/node_modules/y-websocket/bin/server.js:6
const WebSocket = require('ws')
                  ^

ReferenceError: require is not defined
    at file:///xxxxxxx/node_modules/y-websocket/bin/server.js:6:19
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```
**Expected behavior**
a notice to say that y-webserver is running on port 1234

**Environment Information**
node v14.15.1
y-webserver 1.3.14

y-webserver Version 1.3..11 didn't have this problem.

**Comment by istvank** [comment]
I guess this is related to https://github.com/yjs/y-websocket/commit/eba986d325a9673669050120bc3993d2663d992f

If I remove the `"type": "module"`, it works again.

**Comment by dmonad** [comment]
I'm sorry for that. I fixed another bug with that but I broke the server by doing that. I will wait for the next major release to rewrite the server as an ESM module.

I'll shortly release a new version with a fix.
