### ISSUE TITLE
Cannot do require('y-websocket/bin/utils.js') since v1.3.13

### ISSUE THREAD

**Issue by hesselbom** [yjs/y-websocket#73]
**Describe the bug**
I've written my own websocket server based on y-websocket/bin/server.js but instead of rewriting y-websocket/bin/utils.js I've been requiring that file like this:

```js
const yWebsocketUtils = require('y-websocket/bin/utils.js')
```

but since v1.3.13 (where explicit "exports" was added to package.json) I now get this error in Node.js:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/utils.js' is not defined by "exports" in /node_modules/y-websocket/package.json
```

**Expected behavior**
Being able to require subpaths in y-websocket to help custom websocket servers.

**Environment Information**
 - Node.js v12
 - y-websocket v1.3.13

**Comment by hanspagel** [comment]
I think that’s what is described in #72. ✌️

**Comment by hesselbom** [comment]
@hanspagel You're right, that issue covers this so I'll close this!
