### ISSUE TITLE
y-websocket/bin/utils.js file is not accessible anymore the custom persistor solution is not applicable anymore

### ISSUE THREAD

**Issue by abdoolly** [yjs/y-websocket#76]
I admire yjs but, there might be a small problem that happened in y-websocket.

In this issue [https://github.com/yjs/yjs/issues/170](https://github.com/yjs/yjs/issues/170) you purposed the solution which is the code below but, this code is no longer working with adding the `exports` field in the y-websocket and the new node.js versions only allowing subpath exports using the exports field if it exists now we are not able to access `y-websocket/bin/utils.js`

now we are not allowed to require or import `y-websocket/bin/utils.js` if there is an alternative please tell us how or I can raise a PR to solve this issue and add the utils in the exports field.

**NOTE**: I am trying to use y-websocket version **1.3.16**
Node.js version **v12.22.4**

what do you suggest ?

> ```js
> #!/usr/bin/env node
> 
> /**
>  * @type {any}
>  */
> const WebSocket = require('ws')
> const http = require('http')
> const wss = new WebSocket.Server({ noServer: true })
> const utils = require('y-websocket/bin/utils.js')
> const setupWSConnection = utils.setupWSConnection
> 
> const port = process.env.PORT || 1234
> 
> const server = http.createServer((request, response) => {
>   response.writeHead(200, { 'Content-Type': 'text/plain' })
>   response.end('okay')
> })
> 
> /*
>  Persistence must have the following signature:
> { bindState: function(string,WSSharedDoc):void, writeState:function(string,WSSharedDoc):Promise }
> */
> utils.setPersistence({
>   bindState: (documentName, doc) => {
>     // Here you listen to granular document updates and store them in the database
>     // You don't have to do this, but it ensures that you don't lose content when the server crashes
>     // See https://github.com/yjs/yjs#Document-Updates for documentation on how to encode 
>     // document updates
>   },
>   writeState: (string, doc) => {
>     // This is called when all connections to the document are closed.
>     // In the future, this method might also be called in intervals or after a certain number of updates.
>     return new Prosime(resolve => {
>       // When the returned Promise resolves, the document will be destroyed.
>       // So make sure that the document really has been written to the database.
>       resolve()
>     })
>   }
> })
> 
> wss.on('connection', setupWSConnection)
> 
> server.on('upgrade', (request, socket, head) => {
>   // You may check auth of request here..
>   /**
>    * @param {any} ws
>    */
>   const handleAuth = ws => {
>     wss.emit('connection', ws, request)
>   }
>   wss.handleUpgrade(request, socket, head, handleAuth)
> })
> 
> server.listen(port)
> 
> console.log('running on port', port)
> ```

**Comment by Tpuljak** [comment]
I am also facing this issue and am forced to keep y-websocket at version `1.3.6` which exports the `bin` folder.

**Comment by hesselbom** [comment]
A temporary solution is to use [patch-package](https://www.npmjs.com/package/patch-package) by removing the "exports" section (the part that was added [here](https://github.com/yjs/y-websocket/commit/e3615979b42c2f895c1b940d582323840772f4ec#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R28)) of `node_modules/y-websocket/package.json` and then running `yarn patch-package --exclude 'nothing' y-websocket` (or with npx). Make sure `--exclude 'nothing'` is included to include package.json changes in patch.

This way you can use the latest version of y-websocket and still use `require(y-websocket/bin/utils.js)`

**Comment by dmonad** [comment]
I merged the PR that resolves this ticket and will publish a new release in a bit.

**Comment by sabkat-ahmed-rafi** [comment]
> I am also facing this issue and am forced to keep y-websocket at version `1.3.6` which exports the `bin` folder.
