### ISSUE TITLE
I can't check sync status

### ISSUE THREAD

**Issue by vitonsky** [yjs/y-websocket#90]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
In readme we have info about `synced` property of WS provider with description "True if this instance is currently connected and synced with the server."

First of all, this property marked as private in typescript declaration, so we have to cast types to get value.

Well, i have checked value of this property to know current status and this property is always false.

How it work? How i can get current sync status for the document?

**To Reproduce**
1. Create instance of `WebsocketProvider`
2. Wait getting data for your doc
3. Check `doc.provider.synced` any time

**Expected behavior**
Property is reflect of current synchronization status and it's `false` when document is not synced and `true` when we got all data

**Actual behavior**
Property always `false`, so we can't know sync status

**Screenshots**

**Environment Information**
 - Browser
 - y-websocket: 1.3.17, yjs 13.5.17

**Additional context**
I need check current sync status, so `sync` event is not that thing i need

**Comment by vitonsky** [comment]
It's not a library bug

**Comment by thiagodejesus** [comment]
Hi @vitonsky , can please you explain what was causing the issue for you? Also had the problem here and I didn't find the reason
